controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
index:
   path: /{age}
   controller: App\Controller\TestController::index
   defaults :
     age: 0

